// register.ts
const MESSAGES = {
  VALIDATION: {
    USERNAME: {
      INVALID: "Tài khoản không hợp lệ",
    },
    PASSWORD: {
      INVALID: "Mật khẩu không hợp lệ"
    },
    OTP: {
      INVALID: "Mã OTP không hợp lệ",
      OTP_EXPIRED: "Đã hết thời gian xác thực OTP.Hãy yêu cầu gửi lại.",
    },
    DEFAULT: ""


  },
  SUCCESS: {
    OTP_SENT: "Mã OTP đã được gửi đến số điện thoại của bạn",
    REGISTER_SUCCESS: "Đăng ký thành công",
  },
  ERROR: {
    NETWORK: "Lỗi kết nối mạng. Vui lòng thử lại sau.",
    UNKNOWN: "Đã xảy ra lỗi không xác định",
  }
};

const ERROR_CODES = {
  VALIDATION_USERNAME: "VALIDATION_USERNAME",
  VALIDATION_PASSWORD: "VALIDATION_PASSWORD",
  VALIDATION_OTP: "VALIDATION_OTP",

  NETWORK_ERROR: "NETWORK_ERROR",
  OTP_SEND_INVALID: "VALIDATION_FORM",
  OTP_EXPIRED: "OTP_EXPIRED",
  REGISTER_FAILED: "REGISTER_FAILED",
  FORGOTPW_FAILED: "FORGOTPW_FAILED",
  LOGIN_FAILED: "LOGIN_FAILED",
};

const POSITION_MESSAGE = {
  UDL_USERNAME: 'FRGT_MFPU_USN',
  UDL_OTP: 'FRGT_MFPU_OTP',
  UDL_PASSWORD: 'FRGT_MFPU_PW',
  MESSAGES_RES_OK: 'FRGT_MFPU_RES',
  MESSAGES_RES_BAD: 'FRGT_MFPU_RES'
}

// register message fail positions 1 <-> RGT_MP1 -> vị trí hiển thị message UI
// FRGT_MFP_USN -> underline username
const FIELDS = {
  CLIENT_EXPIRED_COUNTDOWN: "otp",

  OTP_CODE_INVALID: POSITION_MESSAGE.UDL_OTP,
  OTP_COED_EXPIRED: POSITION_MESSAGE.UDL_OTP,

  OTP_SENT_OK: POSITION_MESSAGE.MESSAGES_RES_OK,
  OTP_SEND_BAD: POSITION_MESSAGE.MESSAGES_RES_BAD,
  OTP_SEND_INVALID: POSITION_MESSAGE.MESSAGES_RES_BAD,

  OTP_VERIFY_BLOCK: POSITION_MESSAGE.MESSAGES_RES_BAD,
  OTP_VERIFY_BAD: POSITION_MESSAGE.UDL_OTP,

  OTP_RESEND_OK: POSITION_MESSAGE.MESSAGES_RES_OK,
  OTP_RESEND_BAD: POSITION_MESSAGE.UDL_OTP,

  RES_AUTH_BAD: POSITION_MESSAGE.MESSAGES_RES_BAD,

  USERNAME_INVALID: POSITION_MESSAGE.UDL_USERNAME,
  PASSWORD_INVALID: POSITION_MESSAGE.UDL_PASSWORD,


  NETWORK_ERROR: "general",
  UNKNOWN_ERROR: "general",
};



export const AUTH = {
  ERROR_CODES,
  MESSAGES,
  FIELDS,
  POSITION_MESSAGE,
}